*************************** 1. row ***************************
                id: 1
              name: god
          password: 21298df8a3277357ee55b01df9530b535cf08ec1
             email: @god
               key: 
          premdays: 0
premdays_purchased: 0
           lastday: 0
              type: 5
             coins: 0
coins_transferable: 0
  tournament_coins: 0
          creation: 1771879868
           created: 1771879868
            rlname: 
             phone: NULL
          location: 
           country: 
     web_lastlogin: 0
         web_flags: 3
        email_hash: 
         email_new: 
    email_new_time: 0
        email_code: 
        email_next: 0
    email_verified: 0
         recruiter: 0
      house_bid_id: 0
*************************** 1. row ***************************
                             id: 1
                           name: Rook Sample
                       group_id: 1
                     account_id: 1
                          level: 2
                       vocation: 0
                         health: 155
                      healthmax: 155
                     experience: 100
                       lookbody: 113
                       lookfeet: 115
                       lookhead: 95
                       looklegs: 39
                       looktype: 128
                     lookaddons: 0
                       maglevel: 2
                           mana: 60
                        manamax: 60
                      manaspent: 5936
                           soul: 0
                        town_id: 1
                           posx: 32368
                           posy: 32241
                           posz: 7
                     conditions: 
                            cap: 410
                            sex: 1
                        pronoun: 0
                      lastlogin: 0
                         lastip: 0
                           save: 1
                          skull: 0
                      skulltime: 0
                     lastlogout: 0
                      blessings: 0
                     blessings1: 0
                     blessings2: 0
                     blessings3: 0
                     blessings4: 0
                     blessings5: 0
                     blessings6: 0
                     blessings7: 0
                     blessings8: 0
                     onlinetime: 0
                       deletion: 0
                        balance: 0
           offlinetraining_time: 43200
          offlinetraining_skill: -1
                        stamina: 2520
                     skill_fist: 10
               skill_fist_tries: 0
                     skill_club: 12
               skill_club_tries: 155
                    skill_sword: 12
              skill_sword_tries: 155
                      skill_axe: 12
                skill_axe_tries: 155
                     skill_dist: 12
               skill_dist_tries: 93
                skill_shielding: 10
          skill_shielding_tries: 0
                  skill_fishing: 10
            skill_fishing_tries: 0
      skill_critical_hit_chance: 0
skill_critical_hit_chance_tries: 0
      skill_critical_hit_damage: 0
skill_critical_hit_damage_tries: 0
        skill_life_leech_chance: 0
  skill_life_leech_chance_tries: 0
        skill_life_leech_amount: 0
  skill_life_leech_amount_tries: 0
        skill_mana_leech_chance: 0
  skill_mana_leech_chance_tries: 0
        skill_mana_leech_amount: 0
  skill_mana_leech_amount_tries: 0
       skill_criticalhit_chance: 0
       skill_criticalhit_damage: 0
         skill_lifeleech_chance: 0
         skill_lifeleech_amount: 0
         skill_manaleech_chance: 0
         skill_manaleech_amount: 0
                     manashield: 0
                 max_manashield: 0
                xpboost_stamina: 0
                  xpboost_value: 0
                marriage_status: 0
                marriage_spouse: -1
                  bonus_rerolls: 0
                  prey_wildcard: 0
                    task_points: 0
             quickloot_fallback: 0
                  lookmountbody: 0
                  lookmountfeet: 0
                  lookmounthead: 0
                  lookmountlegs: 0
                   currentmount: 0
              lookfamiliarstype: 0
                       isreward: 1
                     istutorial: 0
                         ismain: 0
                    forge_dusts: 0
               forge_dust_level: 100
                randomize_mount: 0
                    boss_points: 0
                 loyalty_points: 0
                 animus_mastery: 
                         virtue: 0
                        harmony: 0
           weapon_proficiencies:   
                        created: 0
                         hidden: 0
                        comment: 
*************************** 2. row ***************************
                             id: 2
                           name: Sorcerer Sample
                       group_id: 1
                     account_id: 1
                          level: 8
                       vocation: 1
                         health: 185
                      healthmax: 185
                     experience: 4200
                       lookbody: 113
                       lookfeet: 115
                       lookhead: 95
                       looklegs: 39
                       looktype: 130
                     lookaddons: 0
                       maglevel: 0
                           mana: 90
                        manamax: 90
                      manaspent: 0
                           soul: 0
                        town_id: 8
                           posx: 32068
                           posy: 30649
                           posz: 6
                     conditions: 
                            cap: 470
                            sex: 1
                        pronoun: 0
                      lastlogin: 0
                         lastip: 0
                           save: 1
                          skull: 0
                      skulltime: 0
                     lastlogout: 0
                      blessings: 0
                     blessings1: 0
                     blessings2: 0
                     blessings3: 0
                     blessings4: 0
                     blessings5: 0
                     blessings6: 0
                     blessings7: 0
                     blessings8: 0
                     onlinetime: 0
                       deletion: 0
                        balance: 0
           offlinetraining_time: 43200
          offlinetraining_skill: -1
                        stamina: 2520
                     skill_fist: 10
               skill_fist_tries: 0
                     skill_club: 10
               skill_club_tries: 0
                    skill_sword: 10
              skill_sword_tries: 0
                      skill_axe: 10
                skill_axe_tries: 0
                     skill_dist: 10
               skill_dist_tries: 0
                skill_shielding: 10
          skill_shielding_tries: 0
                  skill_fishing: 10
            skill_fishing_tries: 0
      skill_critical_hit_chance: 0
skill_critical_hit_chance_tries: 0
      skill_critical_hit_damage: 0
skill_critical_hit_damage_tries: 0
        skill_life_leech_chance: 0
  skill_life_leech_chance_tries: 0
        skill_life_leech_amount: 0
  skill_life_leech_amount_tries: 0
        skill_mana_leech_chance: 0
  skill_mana_leech_chance_tries: 0
        skill_mana_leech_amount: 0
  skill_mana_leech_amount_tries: 0
       skill_criticalhit_chance: 0
       skill_criticalhit_damage: 0
         skill_lifeleech_chance: 0
         skill_lifeleech_amount: 0
         skill_manaleech_chance: 0
         skill_manaleech_amount: 0
                     manashield: 0
                 max_manashield: 0
                xpboost_stamina: 0
                  xpboost_value: 0
                marriage_status: 0
                marriage_spouse: -1
                  bonus_rerolls: 0
                  prey_wildcard: 0
                    task_points: 0
             quickloot_fallback: 0
                  lookmountbody: 0
                  lookmountfeet: 0
                  lookmounthead: 0
                  lookmountlegs: 0
                   currentmount: 0
              lookfamiliarstype: 0
                       isreward: 1
                     istutorial: 0
                         ismain: 0
                    forge_dusts: 0
               forge_dust_level: 100
                randomize_mount: 0
                    boss_points: 0
                 loyalty_points: 0
                 animus_mastery: 
                         virtue: 0
                        harmony: 0
           weapon_proficiencies:   
                        created: 0
                         hidden: 0
                        comment: 
*************************** 3. row ***************************
                             id: 3
                           name: Druid Sample
                       group_id: 1
                     account_id: 1
                          level: 8
                       vocation: 2
                         health: 185
                      healthmax: 185
                     experience: 4200
                       lookbody: 113
                       lookfeet: 115
                       lookhead: 95
                       looklegs: 39
                       looktype: 144
                     lookaddons: 0
                       maglevel: 0
                           mana: 90
                        manamax: 90
                      manaspent: 0
                           soul: 0
                        town_id: 8
                           posx: 32068
                           posy: 30649
                           posz: 6
                     conditions: 
                            cap: 470
                            sex: 1
                        pronoun: 0
                      lastlogin: 0
                         lastip: 0
                           save: 1
                          skull: 0
                      skulltime: 0
                     lastlogout: 0
                      blessings: 0
                     blessings1: 0
                     blessings2: 0
                     blessings3: 0
                     blessings4: 0
                     blessings5: 0
                     blessings6: 0
                     blessings7: 0
                     blessings8: 0
                     onlinetime: 0
                       deletion: 0
                        balance: 0
           offlinetraining_time: 43200
          offlinetraining_skill: -1
                        stamina: 2520
                     skill_fist: 10
               skill_fist_tries: 0
                     skill_club: 10
               skill_club_tries: 0
                    skill_sword: 10
              skill_sword_tries: 0
                      skill_axe: 10
                skill_axe_tries: 0
                     skill_dist: 10
               skill_dist_tries: 0
                skill_shielding: 10
          skill_shielding_tries: 0
                  skill_fishing: 10
            skill_fishing_tries: 0
      skill_critical_hit_chance: 0
skill_critical_hit_chance_tries: 0
      skill_critical_hit_damage: 0
skill_critical_hit_damage_tries: 0
        skill_life_leech_chance: 0
  skill_life_leech_chance_tries: 0
        skill_life_leech_amount: 0
  skill_life_leech_amount_tries: 0
        skill_mana_leech_chance: 0
  skill_mana_leech_chance_tries: 0
        skill_mana_leech_amount: 0
  skill_mana_leech_amount_tries: 0
       skill_criticalhit_chance: 0
       skill_criticalhit_damage: 0
         skill_lifeleech_chance: 0
         skill_lifeleech_amount: 0
         skill_manaleech_chance: 0
         skill_manaleech_amount: 0
                     manashield: 0
                 max_manashield: 0
                xpboost_stamina: 0
                  xpboost_value: 0
                marriage_status: 0
                marriage_spouse: -1
                  bonus_rerolls: 0
                  prey_wildcard: 0
                    task_points: 0
             quickloot_fallback: 0
                  lookmountbody: 0
                  lookmountfeet: 0
                  lookmounthead: 0
                  lookmountlegs: 0
                   currentmount: 0
              lookfamiliarstype: 0
                       isreward: 1
                     istutorial: 0
                         ismain: 0
                    forge_dusts: 0
               forge_dust_level: 100
                randomize_mount: 0
                    boss_points: 0
                 loyalty_points: 0
                 animus_mastery: 
                         virtue: 0
                        harmony: 0
           weapon_proficiencies:   
                        created: 0
                         hidden: 0
                        comment: 
*************************** 4. row ***************************
                             id: 4
                           name: Paladin Sample
                       group_id: 1
                     account_id: 1
                          level: 8
                       vocation: 3
                         health: 185
                      healthmax: 185
                     experience: 4200
                       lookbody: 113
                       lookfeet: 115
                       lookhead: 95
                       looklegs: 39
                       looktype: 129
                     lookaddons: 0
                       maglevel: 0
                           mana: 90
                        manamax: 90
                      manaspent: 0
                           soul: 0
                        town_id: 8
                           posx: 32068
                           posy: 30649
                           posz: 6
                     conditions: 
                            cap: 470
                            sex: 1
                        pronoun: 0
                      lastlogin: 0
                         lastip: 0
                           save: 1
                          skull: 0
                      skulltime: 0
                     lastlogout: 0
                      blessings: 0
                     blessings1: 0
                     blessings2: 0
                     blessings3: 0
                     blessings4: 0
                     blessings5: 0
                     blessings6: 0
                     blessings7: 0
                     blessings8: 0
                     onlinetime: 0
                       deletion: 0
                        balance: 0
           offlinetraining_time: 43200
          offlinetraining_skill: -1
                        stamina: 2520
                     skill_fist: 10
               skill_fist_tries: 0
                     skill_club: 10
               skill_club_tries: 0
                    skill_sword: 10
              skill_sword_tries: 0
                      skill_axe: 10
                skill_axe_tries: 0
                     skill_dist: 10
               skill_dist_tries: 0
                skill_shielding: 10
          skill_shielding_tries: 0
                  skill_fishing: 10
            skill_fishing_tries: 0
      skill_critical_hit_chance: 0
skill_critical_hit_chance_tries: 0
      skill_critical_hit_damage: 0
skill_critical_hit_damage_tries: 0
        skill_life_leech_chance: 0
  skill_life_leech_chance_tries: 0
        skill_life_leech_amount: 0
  skill_life_leech_amount_tries: 0
        skill_mana_leech_chance: 0
  skill_mana_leech_chance_tries: 0
        skill_mana_leech_amount: 0
  skill_mana_leech_amount_tries: 0
       skill_criticalhit_chance: 0
       skill_criticalhit_damage: 0
         skill_lifeleech_chance: 0
         skill_lifeleech_amount: 0
         skill_manaleech_chance: 0
         skill_manaleech_amount: 0
                     manashield: 0
                 max_manashield: 0
                xpboost_stamina: 0
                  xpboost_value: 0
                marriage_status: 0
                marriage_spouse: -1
                  bonus_rerolls: 0
                  prey_wildcard: 0
                    task_points: 0
             quickloot_fallback: 0
                  lookmountbody: 0
                  lookmountfeet: 0
                  lookmounthead: 0
                  lookmountlegs: 0
                   currentmount: 0
              lookfamiliarstype: 0
                       isreward: 1
                     istutorial: 0
                         ismain: 0
                    forge_dusts: 0
               forge_dust_level: 100
                randomize_mount: 0
                    boss_points: 0
                 loyalty_points: 0
                 animus_mastery: 
                         virtue: 0
                        harmony: 0
           weapon_proficiencies:   
                        created: 0
                         hidden: 0
                        comment: 
*************************** 5. row ***************************
                             id: 5
                           name: Knight Sample
                       group_id: 1
                     account_id: 1
                          level: 8
                       vocation: 4
                         health: 185
                      healthmax: 185
                     experience: 4200
                       lookbody: 113
                       lookfeet: 115
                       lookhead: 95
                       looklegs: 39
                       looktype: 131
                     lookaddons: 0
                       maglevel: 0
                           mana: 90
                        manamax: 90
                      manaspent: 0
                           soul: 0
                        town_id: 8
                           posx: 32068
                           posy: 30649
                           posz: 6
                     conditions: 
                            cap: 470
                            sex: 1
                        pronoun: 0
                      lastlogin: 0
                         lastip: 0
                           save: 1
                          skull: 0
                      skulltime: 0
                     lastlogout: 0
                      blessings: 0
                     blessings1: 0
                     blessings2: 0
                     blessings3: 0
                     blessings4: 0
                     blessings5: 0
                     blessings6: 0
                     blessings7: 0
                     blessings8: 0
                     onlinetime: 0
                       deletion: 0
                        balance: 0
           offlinetraining_time: 43200
          offlinetraining_skill: -1
                        stamina: 2520
                     skill_fist: 10
               skill_fist_tries: 0
                     skill_club: 10
               skill_club_tries: 0
                    skill_sword: 10
              skill_sword_tries: 0
                      skill_axe: 10
                skill_axe_tries: 0
                     skill_dist: 10
               skill_dist_tries: 0
                skill_shielding: 10
          skill_shielding_tries: 0
                  skill_fishing: 10
            skill_fishing_tries: 0
      skill_critical_hit_chance: 0
skill_critical_hit_chance_tries: 0
      skill_critical_hit_damage: 0
skill_critical_hit_damage_tries: 0
        skill_life_leech_chance: 0
  skill_life_leech_chance_tries: 0
        skill_life_leech_amount: 0
  skill_life_leech_amount_tries: 0
        skill_mana_leech_chance: 0
  skill_mana_leech_chance_tries: 0
        skill_mana_leech_amount: 0
  skill_mana_leech_amount_tries: 0
       skill_criticalhit_chance: 0
       skill_criticalhit_damage: 0
         skill_lifeleech_chance: 0
         skill_lifeleech_amount: 0
         skill_manaleech_chance: 0
         skill_manaleech_amount: 0
                     manashield: 0
                 max_manashield: 0
                xpboost_stamina: 0
                  xpboost_value: 0
                marriage_status: 0
                marriage_spouse: -1
                  bonus_rerolls: 0
                  prey_wildcard: 0
                    task_points: 0
             quickloot_fallback: 0
                  lookmountbody: 0
                  lookmountfeet: 0
                  lookmounthead: 0
                  lookmountlegs: 0
                   currentmount: 0
              lookfamiliarstype: 0
                       isreward: 1
                     istutorial: 0
                         ismain: 0
                    forge_dusts: 0
               forge_dust_level: 100
                randomize_mount: 0
                    boss_points: 0
                 loyalty_points: 0
                 animus_mastery: 
                         virtue: 0
                        harmony: 0
           weapon_proficiencies:   
                        created: 0
                         hidden: 0
                        comment: 
*************************** 6. row ***************************
                             id: 6
                           name: Monk Sample
                       group_id: 1
                     account_id: 1
                          level: 8
                       vocation: 9
                         health: 185
                      healthmax: 185
                     experience: 4200
                       lookbody: 113
                       lookfeet: 115
                       lookhead: 95
                       looklegs: 39
                       looktype: 1824
                     lookaddons: 0
                       maglevel: 0
                           mana: 90
                        manamax: 90
                      manaspent: 0
                           soul: 0
                        town_id: 8
                           posx: 32068
                           posy: 30649
                           posz: 6
                     conditions: 
                            cap: 470
                            sex: 1
                        pronoun: 0
                      lastlogin: 0
                         lastip: 0
                           save: 1
                          skull: 0
                      skulltime: 0
                     lastlogout: 0
                      blessings: 0
                     blessings1: 0
                     blessings2: 0
                     blessings3: 0
                     blessings4: 0
                     blessings5: 0
                     blessings6: 0
                     blessings7: 0
                     blessings8: 0
                     onlinetime: 0
                       deletion: 0
                        balance: 0
           offlinetraining_time: 43200
          offlinetraining_skill: -1
                        stamina: 2520
                     skill_fist: 10
               skill_fist_tries: 0
                     skill_club: 10
               skill_club_tries: 0
                    skill_sword: 10
              skill_sword_tries: 0
                      skill_axe: 10
                skill_axe_tries: 0
                     skill_dist: 10
               skill_dist_tries: 0
                skill_shielding: 10
          skill_shielding_tries: 0
                  skill_fishing: 10
            skill_fishing_tries: 0
      skill_critical_hit_chance: 0
skill_critical_hit_chance_tries: 0
      skill_critical_hit_damage: 0
skill_critical_hit_damage_tries: 0
        skill_life_leech_chance: 0
  skill_life_leech_chance_tries: 0
        skill_life_leech_amount: 0
  skill_life_leech_amount_tries: 0
        skill_mana_leech_chance: 0
  skill_mana_leech_chance_tries: 0
        skill_mana_leech_amount: 0
  skill_mana_leech_amount_tries: 0
       skill_criticalhit_chance: 0
       skill_criticalhit_damage: 0
         skill_lifeleech_chance: 0
         skill_lifeleech_amount: 0
         skill_manaleech_chance: 0
         skill_manaleech_amount: 0
                     manashield: 0
                 max_manashield: 0
                xpboost_stamina: 0
                  xpboost_value: 0
                marriage_status: 0
                marriage_spouse: -1
                  bonus_rerolls: 0
                  prey_wildcard: 0
                    task_points: 0
             quickloot_fallback: 0
                  lookmountbody: 0
                  lookmountfeet: 0
                  lookmounthead: 0
                  lookmountlegs: 0
                   currentmount: 0
              lookfamiliarstype: 0
                       isreward: 1
                     istutorial: 0
                         ismain: 0
                    forge_dusts: 0
               forge_dust_level: 100
                randomize_mount: 0
                    boss_points: 0
                 loyalty_points: 0
                 animus_mastery: 
                         virtue: 0
                        harmony: 0
           weapon_proficiencies:   
                        created: 0
                         hidden: 0
                        comment: 
*************************** 7. row ***************************
                             id: 7
                           name: GOD
                       group_id: 6
                     account_id: 1
                          level: 2
                       vocation: 0
                         health: 155
                      healthmax: 155
                     experience: 100
                       lookbody: 113
                       lookfeet: 115
                       lookhead: 95
                       looklegs: 39
                       looktype: 302
                     lookaddons: 0
                       maglevel: 0
                           mana: 60
                        manamax: 60
                      manaspent: 0
                           soul: 0
                        town_id: 8
                           posx: 32068
                           posy: 30649
                           posz: 6
                     conditions: 
                            cap: 410
                            sex: 1
                        pronoun: 0
                      lastlogin: 0
                         lastip: 0
                           save: 1
                          skull: 0
                      skulltime: 0
                     lastlogout: 0
                      blessings: 0
                     blessings1: 0
                     blessings2: 0
                     blessings3: 0
                     blessings4: 0
                     blessings5: 0
                     blessings6: 0
                     blessings7: 0
                     blessings8: 0
                     onlinetime: 0
                       deletion: 0
                        balance: 0
           offlinetraining_time: 43200
          offlinetraining_skill: -1
                        stamina: 2520
                     skill_fist: 10
               skill_fist_tries: 0
                     skill_club: 10
               skill_club_tries: 0
                    skill_sword: 10
              skill_sword_tries: 0
                      skill_axe: 10
                skill_axe_tries: 0
                     skill_dist: 10
               skill_dist_tries: 0
                skill_shielding: 10
          skill_shielding_tries: 0
                  skill_fishing: 10
            skill_fishing_tries: 0
      skill_critical_hit_chance: 0
skill_critical_hit_chance_tries: 0
      skill_critical_hit_damage: 0
skill_critical_hit_damage_tries: 0
        skill_life_leech_chance: 0
  skill_life_leech_chance_tries: 0
        skill_life_leech_amount: 0
  skill_life_leech_amount_tries: 0
        skill_mana_leech_chance: 0
  skill_mana_leech_chance_tries: 0
        skill_mana_leech_amount: 0
  skill_mana_leech_amount_tries: 0
       skill_criticalhit_chance: 0
       skill_criticalhit_damage: 0
         skill_lifeleech_chance: 0
         skill_lifeleech_amount: 0
         skill_manaleech_chance: 0
         skill_manaleech_amount: 0
                     manashield: 0
                 max_manashield: 0
                xpboost_stamina: 0
                  xpboost_value: 0
                marriage_status: 0
                marriage_spouse: -1
                  bonus_rerolls: 0
                  prey_wildcard: 0
                    task_points: 0
             quickloot_fallback: 0
                  lookmountbody: 0
                  lookmountfeet: 0
                  lookmounthead: 0
                  lookmountlegs: 0
                   currentmount: 0
              lookfamiliarstype: 0
                       isreward: 1
                     istutorial: 0
                         ismain: 0
                    forge_dusts: 0
               forge_dust_level: 100
                randomize_mount: 0
                    boss_points: 0
                 loyalty_points: 0
                 animus_mastery: 
                         virtue: 0
                        harmony: 0
           weapon_proficiencies:   
                        created: 0
                         hidden: 0
                        comment: 
